# Generated by Django 5.0.2 on 2025-01-30 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('EM_ANDAMENTO', 'Em Andamento'), ('AGUARDANDO_CLIENTE', 'Aguardando Cliente'), ('FECHADO_GANHO', 'Fechado Ganho'), ('FECHADO_PERDIDO', 'Fechado Perdido')], default='NOVO', max_length=20, verbose_name='Status')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=20, verbose_name='Prioridade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_previsao_fechamento', models.DateField(verbose_name='Previsão de Fechamento')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='clientes.cliente')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oportunidade',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-data_cadastro'],
            },
        ),
    ]
