# Generated by Django 5.0.2 on 2025-01-31 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversa_mensagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='lido_por',
            field=models.ManyToManyField(blank=True, related_name='avisos_lidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
