# Generated by Django 5.0.2 on 2025-01-30 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GESTOR', 'Gestor'), ('CORRETOR', 'Corretor')], max_length=10, verbose_name='Tipo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto')),
                ('creci', models.CharField(blank=True, max_length=20, null=True, verbose_name='CRECI')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['usuario__first_name'],
            },
        ),
    ]
