# Generated by Django 5.0.2 on 2025-01-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('GESTOR', 'Gestor'), ('CORRETOR', 'Corretor')], default='CORRETOR', max_length=10, verbose_name='Tipo'),
        ),
    ]
