# Generated by Django 5.0.2 on 2025-01-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_cliente_area_desejada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID do Evento no Google Calendar'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lembrete_minutos',
            field=models.IntegerField(default=30, verbose_name='Minutos para Lembrete'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes_proxima_acao',
            field=models.TextField(blank=True, null=True, verbose_name='Observações da Próxima Ação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_proxima_acao',
            field=models.CharField(blank=True, choices=[('LIGACAO', 'Ligação'), ('VISITA', 'Visita'), ('REUNIAO', 'Reunião'), ('EMAIL', 'E-mail'), ('WHATSAPP', 'WhatsApp')], max_length=20, null=True, verbose_name='Tipo da Próxima Ação'),
        ),
    ]
