# Generated by Django 5.0.2 on 2025-01-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_acaoagendada_historicolead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(choices=[('SEM_CONTATO', 'Sem Contato'), ('EM_NEGOCIACAO', 'Em Negociação'), ('INFO_ERRADA', 'Informação Errada'), ('CLIENTE_RECUSOU', 'Cliente Recusou'), ('CONTRATO_APROVADO', 'Contrato Aprovado'), ('PERDIDO', 'Perdido')], default='NOVO', max_length=20, verbose_name='Status'),
        ),
    ]
