# Generated by Django 5.0.2 on 2025-01-31 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_historicolead_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicolead',
            name='tipo',
            field=models.CharField(choices=[('STATUS', 'Alteração de Status'), ('CONTATO', 'Contato Realizado'), ('AGENDAMENTO', 'Agendamento'), ('OBSERVACAO', 'Observação'), ('DEVOLUCAO', 'Devolução'), ('REDISTRIBUICAO', 'Redistribuição')], max_length=20),
        ),
    ]
