# Generated by Django 5.0.2 on 2025-01-31 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_historicolead_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_atribuicao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
