# Generated by Django 5.0.2 on 2025-01-31 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_data_atribuicao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorretorPunicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_punicao', models.BooleanField(default=False)),
                ('inicio_punicao', models.DateTimeField(blank=True, null=True)),
                ('fim_punicao', models.DateTimeField(blank=True, null=True)),
                ('contagem_devolucoes', models.IntegerField(default=0)),
                ('corretor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='punicao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
